<?xml version="1.0" encoding="UTF-8"?>
<testsuite name="vrielynckpieterjan.masterproef.apilayer.server.ReflectionMethodInvocationServerTest" tests="1" skipped="0" failures="0" errors="0" timestamp="2021-06-20T19:27:14" hostname="MBPvanPieterJan" time="0.055">
  <properties/>
  <testcase name="receiveRequest()" classname="vrielynckpieterjan.masterproef.apilayer.server.ReflectionMethodInvocationServerTest" time="0.055"/>
  <system-out><![CDATA[The test method is called!
]]></system-out>
  <system-err><![CDATA[jun. 20, 2021 9:27:14 P.M. vrielynckpieterjan.masterproef.apilayer.server.ReflectionMethodInvocationServer run
INFO: ReflectionMethodInvocationServer (Thread[Thread-3,5,main]) is running.
jun. 20, 2021 9:27:15 P.M. vrielynckpieterjan.masterproef.apilayer.server.ReflectionMethodInvocationServer run
WARNING: An IOException occurred while trying to handle the next request for ReflectionMethodInvocationServer (Thread[Thread-3,5,main]) (reason: java.io.IOException: First request already handled.).
jun. 20, 2021 9:27:15 P.M. vrielynckpieterjan.masterproef.apilayer.server.ReflectionMethodInvocationServer handleNextRequest
SEVERE: The void vrielynckpieterjan.masterproef.apilayer.server.ReflectionMethodInvocationServerTest$TestReflectionMethodInvocationServer.testMethod(java.lang.String,java.lang.Integer) Method was successfully invoked, but the Method returned (null) while a ReflectionMethodInvocationServerResponse instance was expected.
jun. 20, 2021 9:27:15 P.M. vrielynckpieterjan.masterproef.apilayer.server.ReflectionMethodInvocationServer run
INFO: ReflectionMethodInvocationServer (Thread[Thread-3,5,main]) interrupted; awaiting shutdown...
jun. 20, 2021 9:27:15 P.M. vrielynckpieterjan.masterproef.apilayer.server.ReflectionMethodInvocationServer run
INFO: ReflectionMethodInvocationServer (Thread[Thread-3,5,main]) shut down.
]]></system-err>
</testsuite>
