<?xml version="1.0" encoding="UTF-8"?>
<testsuite name="vrielynckpieterjan.apilayer.server.ReflectionMethodInvocationServerTest" tests="1" skipped="0" failures="0" errors="0" timestamp="2021-04-11T07:53:56" hostname="MacBook-Pro-van-Pieter-Jan.local" time="1.026">
  <properties/>
  <testcase name="receiveRequest()" classname="vrielynckpieterjan.apilayer.server.ReflectionMethodInvocationServerTest" time="1.026"/>
  <system-out><![CDATA[The test method is called!
]]></system-out>
  <system-err><![CDATA[apr. 11, 2021 9:53:56 A.M. vrielynckpieterjan.apilayer.server.ReflectionMethodInvocationServer run
INFO: ReflectionMethodInvocationServer (Thread[Thread-3,5,main]) is running.
apr. 11, 2021 9:53:56 A.M. vrielynckpieterjan.apilayer.server.ReflectionMethodInvocationServer run
WARNING: An IOException occurred while trying to handle the next request for ReflectionMethodInvocationServer (Thread[Thread-3,5,main]) (reason: java.io.IOException: First request already handled.).
apr. 11, 2021 9:53:56 A.M. vrielynckpieterjan.apilayer.server.ReflectionMethodInvocationServer handleNextRequest
SEVERE: The void vrielynckpieterjan.apilayer.server.ReflectionMethodInvocationServerTest$TestReflectionMethodInvocationServer.testMethod(java.lang.String,java.lang.Integer) Method was successfully invoked, but the Method returned (null) while a ReflectionMethodInvocationServerResponse instance was expected.
apr. 11, 2021 9:53:56 A.M. vrielynckpieterjan.apilayer.server.ReflectionMethodInvocationServer run
INFO: ReflectionMethodInvocationServer (Thread[Thread-3,5,main]) interrupted; awaiting termination...
apr. 11, 2021 9:53:57 A.M. vrielynckpieterjan.apilayer.server.ReflectionMethodInvocationServer run
INFO: ReflectionMethodInvocationServer (Thread[Thread-3,5,main]) terminated.
]]></system-err>
</testsuite>
